version: '3.8'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: education

  app:
    image: etap-backend
    ports:
      - "3000:3000"

